### ISSUE TITLE
Deletar branches inativas

### ISSUE THREAD

**Issue by oandrevictor** [italo-batista/monitora-ufcg#8]
quais branches podem ser deletadas?

**Comment by italo-batista** [comment]
basics, drawind-ed

**Comment by italo-batista** [comment]
popup-the-jam tbm, se foi dado merge

**Comment by oandrevictor** [comment]
lembrem: quando terminaram com uma branch: kill it with kindness.
estamos com 7 branches

**Comment by italo-batista** [comment]
Tá dando muita agonia esse monte de Branch. Inclusive essas com uns nomes bem random são as piores, porque fico sem fazer ideia do propósito delas. Isso é muito ruim.

@Rafaela9136 @gabrielmla @gabrielmla @Rafaela9136 @oandrevictor

**Comment by oandrevictor** [comment]
eu só to com uma branch ativa: Edifixes - cujo come é claramente para fazer fixes no edificio
a de gaby é 123Rihanna: Teste
